//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_pedidos
    {
        public int id_pedido { get; set; }
        public Nullable<int> id_produto { get; set; }
        public Nullable<int> qtProdu_pedidos { get; set; }
        public Nullable<decimal> valorTotal_pedido { get; set; }
        public Nullable<int> id_funcionario { get; set; }
        public Nullable<int> id_cardapio { get; set; }
        public Nullable<int> id_fornecedor { get; set; }
    
        public virtual tb_cardapio tb_cardapio { get; set; }
        public virtual tb_fornecedor tb_fornecedor { get; set; }
        public virtual tb_funcionario tb_funcionario { get; set; }
    }
}
